### ISSUE TITLE
DivisionByZeroError on empty store.

### ISSUE THREAD

**Issue by EmericW** [dispositiontools/craft-commerceinsights#1]
Hello,

I just installed this plugin on a new and empty store and received a division by zero error on the `admin/commerceinsights/customers` page.

<img width="869" alt="Screenshot 2022-02-17 at 10 12 26" src="https://user-images.githubusercontent.com/27768755/154443264-6e78116f-2011-4f83-9781-bb0f09e8c55e.png">

**Comment by dispositiontools** [comment]
I'm very sorry!


I'll get this fixed and pushed tomorrow. I'm sorry for this issue.
