### ISSUE TITLE
Missing billing address causes error

### ISSUE THREAD

**Issue by pixelmachine** [dispositiontools/craft-commerceinsights#12]
I have an order that for some reason has no billing address. This causes Commerce Insights (v3 branch) to throw an error.

It looks like the issue is in the Products Service, where there's a check that the Shipping address exists but then data is pulled from the Billing address which may not:

```php
if($shippingAddress){
  $addressShippingDetails = [
    'shippingBusinessName' => $billingAddress->businessName ,
     'shippingFirstName' => $billingAddress->firstName ,
     'shippingLastName' => $billingAddress->lastName ,
     'shippingAddress1' => $billingAddress->address1 ,
     'shippingAddress2' => $billingAddress->address2 ,
     'shippingAddress3' => $billingAddress->address3 ,
     'shippingCity' => $billingAddress->city ,
     'shippingPostcode' => $billingAddress->zipCode ,
   ];
}
```

I assume that's just a typo.

**Comment by dispositiontools** [comment]
thanks for bringing this to my attention - I'll get this fixed today

**Comment by dispositiontools** [comment]
I've pushed the update for the v3 branch with the fix.
tag [v1.0.15](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v1.0.15)
 Thanks again @pixelmachine for spotting this.
