### ISSUE TITLE
MySQL only_full_group_by error on getCustomers

### ISSUE THREAD

**Issue by WHITE-developer** [dispositiontools/craft-commerceinsights#2]
Hi, 

We get this message on the getCustomers method in the CustomersService. Looks like this query is made pre MySQL 5.7.5 due to the 'only_full_group_by' error.

```
Syntax error or access violation: 1055 Expression #15 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'craft.co.email' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

Tested it locally and made this change to make it work on line 126 of src/services/Customers.php
```
->groupBy(['co.customerId'])
```

to 

```
->groupBy(['co.customerId', 'co.email'])
```

If this is fixed that we can start using it in our production enviroments on MySQL 8. Thanks

**Comment by dispositiontools** [comment]
Thank you very much for this. I'm currently working on some refactoring and improvements over multi sites and differences between variants. A fix has now been pushed.
