### ISSUE TITLE
Error when using "Find best selling products"

### ISSUE THREAD

**Issue by maxpdesign** [dispositiontools/craft-commerceinsights#3]
Hello,

I'm getting an error when I use "Find best selling products" functionality.

<img width="1792" alt="Screenshot 2022-08-11 at 11 06 46" src="https://user-images.githubusercontent.com/32506878/184100761-f3de2e38-938c-4baf-b59c-bf0e5c7e7b90.png">

Probably because it is trying to get a purchasable that has been deleted. The docs mention this scenario here: https://craftcms.com/docs/commerce/3.x/purchasables.html#purchasables-and-line-items

Is it possible that you can change the code so it uses the snapshot of the lineItem instead of the getPurchasable() method?
Because the getPurchasable() method is returning null if the purchasable is deleted.

Thanks in advance!

**Comment by dispositiontools** [comment]
Thats a great idea. Thank you. I'll work on this.

**Comment by totov** [comment]
I'm getting the same issue - please let me know if I can supply any info to help diagnose and fix this.

**Comment by dispositiontools** [comment]
Thank you for your patience with this. I've pushed the fix with [v1.0.10](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v1.0.10) 
I've been working on a new version for Craft4 which is more stable and with some new features.
