### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by joshparylak** [dispositiontools/craft-commerceinsights#4]
Is a Craft 4 compatible version planned?

**Comment by dispositiontools** [comment]
Yes indeed. It's being worked on, aiming before the end of the month

**Comment by terryupton** [comment]
Any update on this for Craft 4 at all @dispositiontools?

**Comment by dispositiontools** [comment]
Almost there. Hoping to get it out in the next 7 days

**Comment by jules6120** [comment]
Looking forward to the Craft 4 version as well : )

**Comment by dispositiontools** [comment]
Commerce Insights 4.0.0 has now been released and is available in the Craft Plugin store. Thank you for your patience.
