### ISSUE TITLE
Database error on PostgreSQL

### ISSUE THREAD

**Issue by garrill** [dispositiontools/craft-commerceinsights#5]
Trying to view any of the reports on my site gives the error:

> **Database Exception** – yii\db\Exception
> 
> SQLSTATE[42703]: Undefined column: 7 ERROR: column cli.orderid does not exist
> LINE 3: LEFT JOIN "commerce_orders" "co" ON co.id = cli.orderId
> ^
> HINT: Perhaps you meant to reference the column "cli.orderId".

It looks like query is case sensitive, would this be due to me using PostgreSQL rather than MySQL?

**Comment by dispositiontools** [comment]
Thank you for this, and I'm really sorry you are getting this error. I'll get this sorted.

**Comment by dispositiontools** [comment]
I've looked in to this, and I think i've got a solution, and will be doing some checking this week - it's highlighted a weakness in my release checking - and I need to set up a better PostgreSQL development set up. This will be fixed this week.

**Comment by dispositiontools** [comment]
@garrill Almost done on this. Can I ask if you're using the Craft3 version, or the Craft4 version?

**Comment by garrill** [comment]
Currently on Craft 3, but I’m in the process of upgrading so don’t mind if you if you want to just target 4

**Comment by dispositiontools** [comment]
Thank you for your patience. The new working versions will be pushed this evening to the store. 
I had more to learn about the differences of PostreSQL and MySQL than I care to admit, and I appreciate the prompt to get this sorted.

**Comment by dispositiontools** [comment]
@garrill I've push v4.0.1 which now gives PostgreSQL compatibility when on Craft 4.
