### ISSUE TITLE
Bug: Active Tab is not highlighted correctly

### ISSUE THREAD

**Issue by robzor** [dispositiontools/craft-commerceinsights#6]
Hi there,

Using Craft CMS 4.3.6.1 and Commerce Insights 4.0.1. 

If you click 'Customers' or 'Transactions' in the left hand side nav, 'Products' still remains highlighted.

See attached screenshot:

![CleanShot 2023-01-10 at 4 44 53](https://user-images.githubusercontent.com/704032/211611568-acb4aebc-4b13-494b-a803-6eb069d49a01.png)

**Comment by dispositiontools** [comment]
HI @robzor 
Thanks for this, I'll get this fixed.

**Comment by robzor** [comment]
Thanks!

**Comment by dispositiontools** [comment]
This has now been fixed with  plugin update v4.0.2. Thanks for pointing it out.
