### ISSUE TITLE
Feature Request: Currency display

### ISSUE THREAD

**Issue by robzor** [dispositiontools/craft-commerceinsights#7]
In our store, we only have one currency. In the CMS, the reports show non currency numbers.

It would be great if we could either select this in the Insights options or it pulled it dynamically through from Commerce settings.

**Comment by dispositiontools** [comment]
Yeah - thats a good call. I'll get this updated. Thanks for the feedback

**Comment by robzor** [comment]
Thanks for the plugin! You've made my client (and me) very happy. :)

**Comment by dispositiontools** [comment]
Thanks for that! I'm glad. I've pushed update v4.0.2 which now shows the base currency for now. I'm going to look into making it a plugin setting.
